### ISSUE TITLE
clean up CMakeList and add dependencies to dashboard

### ISSUE THREAD

**Issue by Hansuto** [FlaSpaceInst/EZ-RASSOR#207]
qt-sdk
ros-kinetic-qt-build
qt4-designer (but we're on qt5 afaik?)
libqglviewer-dev-qt4 (")
python-pyqt5 (though we -> sepples)
python-qt4
python-qt4-dbus
python-dbus

**Comment by tgsachse** [comment]
must be reviewed once dashboard is updated. Likely will not need python packages. Working on this now.

**Comment by tgsachse** [comment]
Ditching the dashboard
