### ISSUE TITLE
Add Mars world to ezrassor_sim_gazebo

### ISSUE THREAD

**Issue by CSharpRon** [FlaSpaceInst/EZ-RASSOR#246]
The Mars environment was not fully working with Gazebo 9 and after further investigation, I discovered that the functionality for height maps was actually broken in Gazebo 9.0.0 which is the version that ships with ROS melodic. 

Find another way to add the Mars world to our software with ROS melodic and Gazebo 9.0.0.

**Comment by tgsachse** [comment]
Punting to the next iteration of this project for now
