### ISSUE TITLE
Document the app build process in the wiki

### ISSUE THREAD

**Issue by tgsachse** [FlaSpaceInst/EZ-RASSOR#247]
Build the app and create an apk? automatically. Also possibly include a way to install build dependencies on the development machine automatically?

**Comment by tgsachse** [comment]
fleshed out:
add app-tools and ros-tools commands to wiki, readme, contributing

in develop.sh, add method to start expo, and build android and ios with expo, and set up expo project:
   npm install in project dir etc

**Comment by tgsachse** [comment]
fix script not working at all on fedora etc

**Comment by CSharpRon** [comment]
When you say building the app, do you mean ```npm build``` or ```expo build```? Because I believe that when doing the latter, expo build actually tries to [build the app on expo servers](https://docs.expo.io/versions/latest/distribution/building-standalone-apps/) which means that you need to be logged in to an expo account.

**Comment by tgsachse** [comment]
I meant like, ./develop build app or something and it goes from source code
to compiled on expo and/or APK produced. I don't really know because I know
the least about all that. Maybe it isn't necessary because mobile devs will
just already know how to do it

**Comment by CSharpRon** [comment]
Oh, I got you. The APK build might be unattainable then but yeah, we could build the project for the user through npm build. 

I think you're right though, npm build and npm start are two easy commands that devs would be 100% familiar with so I don't think it would be necessary.

**Comment by tgsachse** [comment]
Could we include a blurb about how to do it, or a link to a page that explains how expo works? For people who dont know. It could go in the wiki, for the controller. You may have added that before in the past and then I got rid of it like an idiot.

**Comment by CSharpRon** [comment]
LOL yes, I will add instructions in the Wiki to document what needs to be installed and how to install it, how to build and run the project, and a general overview of application flow for maintainers.

**Comment by CSharpRon** [comment]
The wiki page was updated succesfully
https://github.com/FlaSpaceInst/EZ-RASSOR/wiki/EZ-RASSOR-Controller
