### ISSUE TITLE
Packages have unmet dependencies 

### ISSUE THREAD

**Issue by agroyy** [FlaSpaceInst/EZ-RASSOR#308]
the following packages have unmet dependencies when installing ros after cloning the repository with the --recursive command:
 ros-kinetic-ros-base : Depends: ros-kinetic-actionlib but it is not going to be installed
                        Depends: ros-kinetic-bond-core but it is not going to be installed
                        Depends: ros-kinetic-class-loader but it is not going to be installed
                        Depends: ros-kinetic-dynamic-reconfigure but it is not going to be installed
                        Depends: ros-kinetic-nodelet-core but it is not going to be installed
                        Depends: ros-kinetic-pluginlib but it is not going to be installed
                        Depends: ros-kinetic-ros-core but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Something went horribly wrong.

**Comment by CSharpRon** [comment]
I'm looking into this but I believe you need to utilize rosdep to install the dependencies that are missing from the project

@tgsachse is this a manual step or was this included in the installation script?

**Comment by tgsachse** [comment]
The script uses rosdep. We need more information. Are you installing Ros manually (thru the ROS wiki instructions) or are you using the installation script in this package?

**Comment by tgsachse** [comment]
In the readme (https://github.com/FlaSpaceInst/EZ-RASSOR/blob/master/docs/README.rst#typical-installation) for the typical installation notice that it says if you get certain dpkg errors there's a command you might want to run to fix it.

Dpkg/apt just randomly fails when installing ROS sometimes. Something to do with package conflicts etc. It's pretty junk tbh but it's out of our control :(

**Comment by CSharpRon** [comment]
@agroyy is this still an issue or can we go ahead and close?

**Comment by agroyy** [comment]
Should be good to close.

**Comment by CSharpRon** [comment]
Closing issue since ROS dep needs to be used.
