### ISSUE TITLE
Mobile App not working

### ISSUE THREAD

**Issue by gilchristb20** [FlaSpaceInst/EZ-RASSOR#323]
The mobile app listed under EZ RASSOR Controller is not updated so it is unable to be downloaded. when you click the link to download [here](https://expo.io/@camilozano/ControllerApp), Expo states that the project is out of date and must be updated from Expo SDK v31.0.0 to Expo SDK v33.0.0

**Comment by CSharpRon** [comment]
Apologies, we created a separate account in Expo and the link you have should be deprecated. Use https://expo.io/@ez-rassor/EZRASSORController instead

Also, where does that link exist in the documentation? Is it in the Wiki?

**Comment by CSharpRon** [comment]
Also, the app is live on the Play Store https://play.google.com/store/apps/details?id=com.FlaSpaceInst.EZRASSORController

**Comment by gilchristb20** [comment]
the link is located in the wiki under EZ RASSOR Controller

**Comment by CSharpRon** [comment]
Thank you, just need a few hours before I'm back online to fix the link. Then I'll close the issue

**Comment by CSharpRon** [comment]
Updated the wiki and the links are live. Thank you for the heads up @gilchristb20 !
