### ISSUE TITLE
Rename the Master branch to match the LTS release

### ISSUE THREAD

**Issue by CSharpRon** [FlaSpaceInst/EZ-RASSOR#333]
The EZ-RASSOR software is currently built with ROS Melodic, which is the LTS for Ubuntu 18.04 LTS. 

[ROS Noetic Ninjemys](https://wiki.ros.org/noetic) is coming out at the end of May for the 20.04 LTS. We should test the software for that release when it comes out and create a new branch indicating that software changes are for that release. 

However at a minimum for this issue I believe we should rename "Master" to "melodic-devel" or something similar for future-proofing.
Look at the branches for these repos to see where I'm getting this idea from:
[universal robot](https://github.com/ros-industrial/universal_robot)
[turtlebot3](https://github.com/ROBOTIS-GIT/turtlebot3)

**Comment by tigressine** [comment]
Will do this in upcoming repository split.
