### ISSUE TITLE
Investigate ROS2 migration effort

### ISSUE THREAD

**Issue by tigressine** [FlaSpaceInst/EZ-RASSOR#362]

**Comment by tigressine** [comment]
This is underway, will be tracked alongside https://github.com/FlaSpaceInst/EZ-RASSOR/issues/359

**Comment by soldierofhell** [comment]
Hi @tgsachse, any work has been done towards ROS2 support? Regards,

**Comment by CSharpRon** [comment]
> Hi @tgsachse, any work has been done towards ROS2 support? Regards,

Hey, we have been making progress on our conversion efforts and I've logged our current status in #359.

**Comment by tigressine** [comment]
We also have a kanban board where we are tracking our progress: https://github.com/orgs/FlaSpaceInst/projects/1
