### ISSUE TITLE
Produce a report of all the settings in the simulation environment and the results

### ISSUE THREAD

**Issue by CSharpRon** [FlaSpaceInst/EZ-RASSOR#84]
This is a final report that can look however we want. Basically just useful findings for teams going forward.

**Comment by tgsachse** [comment]
Do you plan to do this before the semester starts?

**Comment by CSharpRon** [comment]
This probably requires some discussion. It's low on the priority list and our simulation model isn't going to look like the final hardware in terms of scale. 

I'll put it on my list of V1.1 tasks, but it's at the end of the list. The other items are more important.

**Comment by tgsachse** [comment]
Deprioritized.
